mlflow:
  experiment_name: Ship_classification
  run_name: test
dataset:
  train_path: ../data/set-A_train
  test_path: ../data/set-B_test
  num_classes: 13
  resize: 64
  batch_size: 128
  train_ratio: 0.8
model:
  dropout: 0.3
  hidden_dim: 32
train:
  device: mps
  epochs: 10
  lr: 0.005